default: &default
  adapter: sqlite3
  timeout: 5000

development:
  <<: *default
  database: db/portfolios-dev.sqlite3

production:
  <<: *default
  database: db/portfolios-prod.db

test:
  <<: *default
  database: db/portfolios-test.sqlite3
